export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCEEDED = "MOVIE_DETAILS_SUCCEEDED";
export const MOVIE_DETAILS_ERROR = "MOVIE_DETAILS_ERROR";

export const NOW_PLAYING_MOVIES_REQUEST = "NOW_PLAYING_MOVIES_REQUEST";
export const NOW_PLAYING_MOVIES_SUCCEEDED = "NOW_PLAYING_MOVIES_SUCCEEDED";
export const NOW_PLAYING_MOVIES_LIST_ERROR = "NOW_PLAYING_MOVIES_LIST_ERROR";

export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_SUCCEEDED = "MOVIES_LIST_SUCCEEDED";
export const MOVIES_LIST_ERROR = "MOVIES_LIST_ERROR";
export const CLEAR_MOVIE_DETAILS = "CLEAR_MOVIE_DETAILS";
