export const REVIEW_REQUEST = "REVIEW_REQUEST";
export const REVIEW_SUCCEEDED = "REVIEW_SUCCEEDED";
export const REVIEW_ERROR = "REVIEW_ERROR";
export const CLEAR_REVIEW_DETAILS= "CLEAR_REVIEW_DETAILS";
