export const SHOWS_LIST_REQUEST = "SHOWS_LIST_REQUEST";
export const SHOWS_LIST_SUCCEEDED = "SHOWS_LIST_SUCCEEDED";
export const SHOWS_LIST_ERROR = "SHOWS_LIST_ERROR";
export const CLEAR_SHOWS_LIST= "CLEAR_SHOWS_LIST";
