export const TICKETS_LIST_USER_REQUEST = "TICKETS_LIST_USER_REQUEST";
export const TICKETS_LIST_USER_SUCCEEDED = "TICKETS_LIST_USER_SUCCEEDED";
export const TICKETS_LIST_USER_ERROR = "TICKETS_LIST_USER_ERROR";
export const CLEAR_TICKETS_LIST_USER = "CLEAR_TICKETS_LIST_USER";

export const TICKET_CANCEL_REQUEST = "TICKET_CANCEL_REQUEST";
export const TICKET_CANCEL_SUCCEEDED = "TICKET_CANCEL_SUCCEEDED";
export const TICKET_CANCEL_ERROR= "TICKET_CANCEL_ERROR";

export const TICKET_BOOKING_REQUEST = "TICKET_BOOKING_REQUEST";
export const TICKET_BOOKING_SUCCEEDED = "TICKET_BOOKING_SUCCEEDED";
export const TICKET_BOOKING_ERROR = "TICKET_BOOKING_ERROR";
export const CLEAR_TICKET_BOOKING = "CLEAR_TICKET_BOOKING";