export const USERS_LIST_REQUEST = "USERS_LIST_REQUEST";
export const USERS_LIST_SUCCEEDED = "USERS_LIST_SUCCEEDED";
export const USERS_LIST_ERROR = "USERS_LIST_ERROR";

export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCEEDED = "REGISTRATION_SUCCEEDED";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const CLEAR_REGISTRATION_DETAILS = "CLEAR_REGISTRATION_DETAILS";
